/**
 * generate_sdk — Generate ready-to-use SDK from reversed API contract
 *
 * Produces Python/Node/Go SDK with: request construction, crypto signing,
 * error handling, and usage example.
 */
import type { McpToolResult } from '../types.js';

interface SignSpec {
  algorithm: string;
  keySource: string;
  signLocation?: 'header' | 'query' | 'body';
  signField?: string;
  paramsToSign?: string[];
}

interface LoginSpec {
  url: string;
  usernameField: string;
  passwordField: string;
  passwordEncryption?: string;
  tokenField?: string;
}

interface ApiSpec {
  url: string;
  method?: string;
  headers?: Record<string, string>;
  bodyTemplate?: string;
  signSpec?: SignSpec;
  loginSpec?: LoginSpec;
}

export async function generateSdk(apiSpec: ApiSpec, language: string): Promise<McpToolResult> {
  const method = (apiSpec.method ?? 'POST').toUpperCase();
  const signField = apiSpec.signSpec?.signField ?? 'sign';
  const signLocation = apiSpec.signSpec?.signLocation ?? 'header';
  const tokenField = apiSpec.loginSpec?.tokenField ?? 'token';

  let code = '';

  if (language === 'python') {
    code = generatePythonSdk(apiSpec, method, signField, signLocation, tokenField);
  } else if (language === 'node') {
    code = generateNodeSdk(apiSpec, method, signField, signLocation, tokenField);
  } else {
    code = generateGoSdk(apiSpec, method, signField, signLocation, tokenField);
  }

  const result = {
    language,
    apiEndpoint: apiSpec.url,
    method,
    signAlgorithm: apiSpec.signSpec?.algorithm ?? 'none',
    signLocation,
    signField,
    hasLoginFlow: !!apiSpec.loginSpec,
    sdk: code,
    usageExample: generateUsageExample(apiSpec, language),
  };

  return {
    content: [{ type: 'text', text: JSON.stringify(result, null, 2) }],
  };
}

function generatePythonSdk(
  spec: ApiSpec,
  method: string,
  signField: string,
  signLocation: string,
  tokenField: string,
): string {
  const lines: string[] = [];
  lines.push('#!/usr/bin/env python3');
  lines.push('"""');
  lines.push(`SDK for ${spec.url}`);
  lines.push(`Generated by crypto-reverse-mcp`);
  lines.push('"""');
  lines.push('import hashlib');
  lines.push('import hmac');
  lines.push('import json');
  lines.push('import time');
  lines.push('from typing import Any, Optional');
  lines.push('from urllib.parse import urlencode');
  lines.push('');
  lines.push('try:');
  lines.push('    import requests');
  lines.push('except ImportError:');
  lines.push('    raise ImportError("pip install requests")');
  lines.push('');
  lines.push('');
  lines.push(`class ${getSdkClassName(spec.url)}:`);
  lines.push('    """API SDK with automatic request signing"""');
  lines.push('');
  lines.push(`    BASE_URL = ${JSON.stringify(spec.url)}`);
  lines.push('    TIMEOUT = 30');
  lines.push('');

  // __init__
  lines.push('    def __init__(self, app_key: str = "", app_secret: str = "", token: str = ""):');
  lines.push('        self.app_key = app_key');
  lines.push('        self.app_secret = app_secret  # Used for HMAC signing');
  lines.push('        self.token = token  # Set after login');
  lines.push('        self.session = requests.Session()');
  if (spec.headers) {
    lines.push('        self.session.headers.update({');
    for (const [k, v] of Object.entries(spec.headers)) {
      lines.push(`            ${JSON.stringify(k)}: ${JSON.stringify(v)},`);
    }
    lines.push('        })');
  }
  lines.push('');

  // _sign
  if (spec.signSpec) {
    lines.push('    def _sign(self, params: dict) -> str:');
    const algo = spec.signSpec.algorithm.toUpperCase();
    if (algo.includes('HMAC') || algo.includes('SHA256')) {
      lines.push(`        """Generate ${spec.signSpec.algorithm} signature"""`);
      lines.push(`        # Key source: ${spec.signSpec.keySource}`);
      lines.push('        sign_params = {k: v for k, v in params.items() if v is not None}');
      if (spec.signSpec.paramsToSign && spec.signSpec.paramsToSign.length > 0) {
        lines.push(`        sign_keys = ${JSON.stringify(spec.signSpec.paramsToSign)}`);
        lines.push('        sign_str = "&".join(f"{k}={sign_params.get(k, "")}" for k in sign_keys)');
      } else {
        lines.push('        sign_str = "&".join(f"{k}={v}" for k, v in sorted(sign_params.items()))');
      }
      lines.push('        sign_str += self.app_secret');
      lines.push("        return hmac.new(self.app_secret.encode(), sign_str.encode(), hashlib.sha256).hexdigest()");
    } else if (algo.includes('MD5')) {
      lines.push(`        """Generate MD5 signature"""`);
      lines.push('        sign_params = {k: v for k, v in params.items() if v is not None}');
      lines.push('        sign_str = "&".join(f"{k}={v}" for k, v in sorted(sign_params.items()))');
      lines.push('        sign_str += self.app_secret');
      lines.push("        return hashlib.md5(sign_str.encode()).hexdigest()");
    } else {
      lines.push(`        """Generate ${spec.signSpec.algorithm} signature (TODO: implement)"""`);
      lines.push('        # TODO: implement specific signing logic');
      lines.push('        raise NotImplementedError(' + JSON.stringify(spec.signSpec.algorithm) + ')');
    }
    lines.push('');
  }

  // _request
  lines.push('    def _request(self, endpoint: str, params: dict = None, data: dict = None, need_sign: bool = True) -> dict:');
  lines.push('        """Internal request method with auto-signing"""');
  lines.push('        url = self.BASE_URL + endpoint if not endpoint.startswith("http") else endpoint');
  lines.push('        params = params or {}');
  lines.push('');
  lines.push('        # Add common params');
  lines.push('        params.setdefault("app_key", self.app_key)');
  lines.push('        params.setdefault("timestamp", str(int(time.time())))');
  lines.push('        if self.token:');
  lines.push(`            params.setdefault("token", self.token)`);
  lines.push('');
  // Sign
  if (spec.signSpec) {
    lines.push('        if need_sign:');
    lines.push(`            sign = self._sign(params)`);
    if (signLocation === 'header') {
      lines.push(`            headers = {${JSON.stringify(signField)}: sign}`);
      lines.push('        else:');
      lines.push('            headers = {}');
    } else if (signLocation === 'query') {
      lines.push(`            params[${JSON.stringify(signField)}] = sign`);
      lines.push('        headers = {}');
    } else {
      lines.push(`            data = data or {}`);
      lines.push(`            data[${JSON.stringify(signField)}] = sign`);
      lines.push('        headers = {}');
    }
  } else {
    lines.push('        headers = {}');
  }
  lines.push('');
  lines.push(`        response = self.session.request(`);
  lines.push(`            ${JSON.stringify(method)},`);
  lines.push('            url,');
  lines.push('            params=params if ' + JSON.stringify(method) + ' in ("GET", "DELETE") else None,');
  lines.push('            json=data if ' + JSON.stringify(method) + ' in ("POST", "PUT", "PATCH") else None,');
  lines.push('            headers=headers,');
  lines.push('            timeout=self.TIMEOUT,');
  lines.push('        )');
  lines.push('        response.raise_for_status()');
  lines.push('        return response.json()');
  lines.push('');

  // Login
  if (spec.loginSpec) {
    lines.push('    def login(self, username: str, password: str) -> str:');
    lines.push('        """Login and store token"""');
    if (spec.loginSpec.passwordEncryption) {
      lines.push(`        # Password encrypted with: ${spec.loginSpec.passwordEncryption}`);
      lines.push('        encrypted_password = self._encrypt_password(password)');
    } else {
      lines.push('        encrypted_password = password');
    }
    lines.push('        result = self._request(');
    lines.push(`            ${JSON.stringify(spec.loginSpec.url)},`);
    lines.push('            data={');
    lines.push(`                ${JSON.stringify(spec.loginSpec.usernameField)}: username,`);
    lines.push(`                ${JSON.stringify(spec.loginSpec.passwordField)}: encrypted_password,`);
    lines.push('            },');
    lines.push('            need_sign=False,');
    lines.push('        )');
    lines.push(`        self.token = result.get(${JSON.stringify(tokenField)}, "")`);
    lines.push('        return self.token');
    lines.push('');
  }

  // _encrypt_password
  if (spec.loginSpec?.passwordEncryption) {
    lines.push('    def _encrypt_password(self, password: str) -> str:');
    lines.push(`        """Encrypt password using ${spec.loginSpec.passwordEncryption}"""`);
    lines.push('        # TODO: implement based on reversed algorithm');
    lines.push('        # Use reconstruct_algorithm tool to get the implementation');
    lines.push('        return password  # placeholder');
    lines.push('');
  }

  return lines.join('\n');
}

function generateNodeSdk(
  spec: ApiSpec,
  method: string,
  signField: string,
  signLocation: string,
  tokenField: string,
): string {
  const lines: string[] = [];
  lines.push('#!/usr/bin/env node');
  lines.push(`// SDK for ${spec.url}`);
  lines.push('// Generated by crypto-reverse-mcp');
  lines.push('');
  lines.push("const crypto = require('crypto');");
  lines.push("const http = require('http');");
  lines.push("const https = require('https');");
  lines.push("const { URL } = require('url');");
  lines.push('');
  lines.push(`class ${getSdkClassName(spec.url)} {`);
  lines.push('  constructor({ appKey = "", appSecret = "", token = "" } = {}) {');
  lines.push('    this.appKey = appKey;');
  lines.push('    this.appSecret = appSecret;');
  lines.push('    this.token = token;');
  lines.push(`    this.baseUrl = ${JSON.stringify(spec.url)};`);
  lines.push('    this.timeout = 30000;');
  lines.push('  }');
  lines.push('');

  if (spec.signSpec) {
    lines.push('  _sign(params) {');
    const algo = spec.signSpec.algorithm.toUpperCase();
    lines.push(`    // ${spec.signSpec.algorithm} signature`);
    lines.push(`    // Key source: ${spec.signSpec.keySource}`);
    lines.push('    const sorted = Object.keys(params).sort().map(k => `${k}=${params[k]}`).join("&");');
    lines.push('    const signStr = sorted + this.appSecret;');
    if (algo.includes('MD5')) {
      lines.push("    return crypto.createHash('md5').update(signStr).digest('hex');");
    } else {
      lines.push("    return crypto.createHmac('sha256', this.appSecret).update(signStr).digest('hex');");
    }
    lines.push('  }');
    lines.push('');
  }

  lines.push('  async _request(endpoint, { params = {}, data = null, needSign = true } = {}) {');
  lines.push('    const url = new URL(endpoint.startsWith("http") ? endpoint : this.baseUrl + endpoint);');
  lines.push('    params.app_key = this.appKey;');
  lines.push('    params.timestamp = Math.floor(Date.now() / 1000).toString();');
  lines.push('    if (this.token) params.token = this.token;');
  lines.push('');
  if (spec.signSpec) {
    lines.push('    let headers = {};');
    lines.push('    if (needSign) {');
    lines.push('      const sign = this._sign(params);');
    if (signLocation === 'header') {
      lines.push(`      headers[${JSON.stringify(signField)}] = sign;`);
    } else if (signLocation === 'query') {
      lines.push(`      params[${JSON.stringify(signField)}] = sign;`);
    } else {
      lines.push(`      data = data || {};`);
      lines.push(`      data[${JSON.stringify(signField)}] = sign;`);
    }
    lines.push('    }');
  } else {
    lines.push('    const headers = {};');
  }
  lines.push('');
  lines.push('    Object.keys(params).forEach(k => url.searchParams.set(k, params[k]));');
  lines.push('');
  lines.push(`    return new Promise((resolve, reject) => {`);
  lines.push(`      const options = {`);
  lines.push(`        method: ${JSON.stringify(method)},`);
  lines.push(`        hostname: url.hostname,`);
  lines.push(`        path: url.pathname + url.search,`);
  lines.push(`        headers: { ...headers, "Content-Type": "application/json" },`);
  lines.push(`      };`);
  lines.push(`      const req = (url.protocol === "https:" ? https : http).request(options, res => {`);
  lines.push(`        let body = "";`);
  lines.push(`        res.on("data", chunk => body += chunk);`);
  lines.push(`        res.on("end", () => {`);
  lines.push(`          try { resolve(JSON.parse(body)); }`);
  lines.push(`          catch { resolve(body); }`);
  lines.push(`        });`);
  lines.push(`      });`);
  lines.push(`      req.on("error", reject);`);
  lines.push(`      req.setTimeout(this.timeout, () => req.destroy(new Error("timeout")));`);
  lines.push(`      if (data) req.write(JSON.stringify(data));`);
  lines.push(`      req.end();`);
  lines.push(`    });`);
  lines.push('  }');
  lines.push('');

  if (spec.loginSpec) {
    lines.push('  async login(username, password) {');
    if (spec.loginSpec.passwordEncryption) {
      lines.push(`    // Password encrypted with: ${spec.loginSpec.passwordEncryption}`);
      lines.push('    const encryptedPassword = this._encryptPassword(password);');
    } else {
      lines.push('    const encryptedPassword = password;');
    }
    lines.push('    const result = await this._request(');
    lines.push(`      ${JSON.stringify(spec.loginSpec.url)},`);
    lines.push(`      { data: { ${JSON.stringify(spec.loginSpec.usernameField)}: username, ${JSON.stringify(spec.loginSpec.passwordField)}: encryptedPassword }, needSign: false }`);
    lines.push('    );');
    lines.push(`    this.token = result.${tokenField} || "";`);
    lines.push('    return this.token;');
    lines.push('  }');
    lines.push('');
  }

  lines.push('}');
  lines.push('');
  lines.push('module.exports = ' + getSdkClassName(spec.url) + ';');

  return lines.join('\n');
}

function generateGoSdk(
  spec: ApiSpec,
  method: string,
  signField: string,
  signLocation: string,
  tokenField: string,
): string {
  const lines: string[] = [];
  lines.push(`// SDK for ${spec.url}`);
  lines.push('// Generated by crypto-reverse-mcp');
  lines.push('package main');
  lines.push('');
  lines.push('import (');
  lines.push('\t"crypto/hmac"');
  lines.push('\t"crypto/sha256"');
  lines.push('\t"encoding/hex"');
  lines.push('\t"encoding/json"');
  lines.push('\t"fmt"');
  lines.push('\t"io"');
  lines.push('\t"net/http"');
  lines.push('\t"net/url"');
  lines.push('\t"sort"');
  lines.push('\t"strings"');
  lines.push('\t"time"');
  lines.push(')');
  lines.push('');
  lines.push(`type ${getSdkClassName(spec.url)} struct {`);
  lines.push('\tAppKey    string');
  lines.push('\tAppSecret string');
  lines.push('\tToken     string');
  lines.push('\tBaseURL   string');
  lines.push('\tClient    *http.Client');
  lines.push('}');
  lines.push('');
  lines.push(`func New${getSdkClassName(spec.url)}(appKey, appSecret string) *${getSdkClassName(spec.url)} {`);
  lines.push('\treturn &' + getSdkClassName(spec.url) + '{');
  lines.push(`\t\tAppKey: appKey, AppSecret: appSecret,`);
  lines.push(`\t\tBaseURL: ${JSON.stringify(spec.url)},`);
  lines.push('\t\tClient: &http.Client{Timeout: 30 * time.Second},');
  lines.push('\t}');
  lines.push('}');
  lines.push('');

  if (spec.signSpec) {
    lines.push(`func (s *${getSdkClassName(spec.url)}) sign(params map[string]string) string {`);
    lines.push('\tkeys := make([]string, 0, len(params))');
    lines.push('\tfor k := range params { keys = append(keys, k) }');
    lines.push('\tsort.Strings(keys)');
    lines.push('\tvar b strings.Builder');
    lines.push('\tfor _, k := range keys {');
    lines.push('\t\tfmt.Fprintf(&b, "%s=%s&", k, params[k])');
    lines.push('\t}');
    lines.push('\tb.WriteString(s.AppSecret)');
    lines.push('\th := hmac.New(sha256.New, []byte(s.AppSecret))');
    lines.push('\th.Write([]byte(b.String()))');
    lines.push('\treturn hex.EncodeToString(h.Sum(nil))');
    lines.push('}');
    lines.push('');
  }

  return lines.join('\n');
}

function getSdkClassName(url: string): string {
  try {
    const u = new URL(url);
    const parts = u.hostname.split('.').filter((p) => p && p !== 'www');
    const name = parts[0] ?? 'Api';
    return name.charAt(0).toUpperCase() + name.slice(1) + 'SDK';
  } catch {
    return 'ApiSDK';
  }
}

function generateUsageExample(spec: ApiSpec, language: string): string {
  const className = getSdkClassName(spec.url);
  if (language === 'python') {
    return `# Usage
sdk = ${className}(app_key="your_app_key", app_secret="your_secret")
${spec.loginSpec ? '# Login first\ntoken = sdk.login("username", "password")\n' : ''}# Call API
result = sdk._request("/api/endpoint", params={"key": "value"})
print(result)`;
  } else if (language === 'node') {
    return `// Usage
const sdk = new ${className}({ appKey: "your_app_key", appSecret: "your_secret" });
${spec.loginSpec ? '// Login\nawait sdk.login("username", "password");\n' : ''}// Call API
const result = await sdk._request("/api/endpoint", { params: { key: "value" } });
console.log(result);`;
  }
  return `// Usage
sdk := New${className}("your_app_key", "your_secret")
// TODO: implement API call`;
}
